name = "santums-build"
main = "_worker.js"
compatibility_date = "2025-11-11"
compatibility_flags = ["nodejs_compat"]

# ğŸ‘‡ This line tells Cloudflare Pages where to find the build output
pages_build_output_dir = ".next"

[build]
command = "npm run build"
